swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /pim/{pimId}:
    get:
      description: Returns persisted and identified data (PIM)
      # used as the method name of the controller
      operationId: getPim
      parameters:
        - in: path
          name: pimId
          description: ID of pim
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/pim"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /pim:
    # binds a127 app logic to a route
    x-swagger-router-controller: pim
    post:
      description: Creates persisted and identified data (PIM)
      consumes:
      - "application/json"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/pim"
      responses:
        "201":
          description: Created
  /schema/{schemaId}:
    # binds a127 app logic to a route
    x-swagger-router-controller: schema
    get:
      description: Returns schema that was posted as a PIM
      # used as the method name of the controller
      operationId: getSchema
      parameters:
        - in: path
          name: schemaId
          description: ID of schema
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/pimSchmema"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /schema:
    # binds a127 app logic to a route
    x-swagger-router-controller: schema
    post:
      description: Creates schema to be used with (PIM)
      consumes:
      - "application/json"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/pimSchmema"
      responses:
        "201":
          description: Created
# complex objects have schema definitions
definitions:
  pim:
    required:
      - schemaId
      - metadata
    properties:
      schemaId:
        description: ID of schema used to verify the metadata is valid (enforced at the webapp level). 
        type: string
      supersedes:
        description: ID of another PIM this PIM supersedes...only PIM owners should use this (enforced at the webapp level).
        type: string
      metadata:
        description: Metadata to be persisted
        type: object
        
  pimSchmema:
    required:
      - schema
    properties:
      supersedes:
        description: ID of another PIM this PIM supersedes...only PIM owners should use this (enforced at the webapp level).
        type: string
      schema:
        description: JSON schema used to validate PIMs
        type: object

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
